name: fifflar_uffe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  archive: ^4.0.0
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: perf/component-set-backing
      path: packages/flame
  flutter:
    sdk: flutter
  flutter_soloud: ^4.1.7
  gal: ^2.3.3
  share_plus: ^13.3.0
  shared_preferences: ^2.5.0
  supabase_flutter:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/supabase_flutter
  url_launcher: ^6.3.0
  web: ^1.1.1

dev_dependencies:
  flame_lint:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: main
      path: packages/flame_lint
  flame_test:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: perf/component-set-backing
      path: packages/flame_test
  flutter_test:
    sdk: flutter

dependency_overrides:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: perf/component-set-backing
      path: packages/flame
  iceberg:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/iceberg
  postgrest:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/postgrest
  supabase:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/supabase
  supabase_auth:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/supabase_auth
  supabase_common:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/supabase_common
  supabase_functions:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/supabase_functions
  supabase_realtime:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/supabase_realtime
  supabase_storage:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/supabase_storage
  yet_another_json_isolate:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/yet_another_json_isolate

flutter:
  uses-material-design: true
  assets:
    - assets/data/events.json
    - assets/sounds/coin_1.mp3
    - assets/sounds/coin_2.mp3
    - assets/sounds/coin_3.mp3
    - assets/sounds/door_1.mp3
    - assets/sounds/door_2.mp3
    - assets/sounds/door_3.mp3
    - assets/sounds/fanfare.mp3
    - assets/sounds/broken_glass.mp3
    - assets/sounds/laugh.mp3
    - assets/images/Icons/IconsDefault/128px/IconsDefault11_128px.png
    - assets/images/Icons/IconsDefault/128px/IconsDefault12_128px.png
    - assets/images/Icons/IconsDefault/128px/IconsDefault14_128px.png
    - assets/images/Icons/IconsDefault/128px/IconsDefault21_128px.png
    - assets/images/Icons/IconsDefault/128px/IconsDefault25_128px.png
    - assets/images/Icons/IconsDefault/128px/IconsDefault26_128px.png
    - assets/images/skills/hire_cleaner.png
    - assets/images/skills/cheat_apartment.png
    - assets/images/skills/taxi_rides.png
    - assets/images/skills/china_trips.png
    - assets/images/skills/furnish_palace.png
    - assets/images/skills/write_book.png
    - assets/images/skills/lower_taxes.png
    - assets/images/skills/break_promise.png
    - assets/images/skills/cut_sick_leave.png
    - assets/images/skills/privatize_schools.png
    - assets/images/skills/privatize_hospitals.png
    - assets/images/skills/sell_preschools.png
    - assets/images/skills/sell_public_housing.png
    - assets/images/Buttons/Round/RoundButton2_green.png
    - assets/images/Buttons/Round/RoundButton2_lime.png
    - assets/images/Buttons/Round/RoundButton2_blue.png
    - assets/images/Buttons/Round/RoundButton2_turquoise.png
    - assets/images/Buttons/Round/RoundButton2_gray.png
    - assets/images/Buttons/Round/RoundButton2_yellow_dark.png
    - assets/images/Buttons/Round/RoundButton2_cream.png
    - assets/images/Buttons/Round/RoundButton1_white.png
    - assets/images/Buttons/Round/RoundButton1_gray.png
    - assets/images/Labels/Label1.png
    - assets/images/Headers/Header1.png
    - assets/images/Containers/Containers/Container2.png
    - assets/images/Inventory/InventoryModal.png
    - assets/images/Inventory/ItemSlots/ItemSlotsDefault/ItemSlot1.png
    - assets/images/Checkboxes/Radiobutton_checked.png
    - assets/images/Checkboxes/Radiobutton_unchecked.png
    - assets/images/flag_sv.png
    - assets/images/flag_en.png
    - assets/images/speech_bubble.png
    - assets/images/uffe_head.png
    - assets/images/uffe_body.png
    - assets/images/riksdag_bg.jpg
