import 'package:fifflar_uffe/game/assets.dart';
import 'package:fifflar_uffe/model/skill_def.dart';
import 'package:fifflar_uffe/model/skill_id.dart';

final List<SkillDef> skillCatalog = [
  SkillDef(
    id: SkillId.hireCleaner,
    iconPath: AssetPaths.iconPeople,
    name: (strings) => strings.itemHireCleaner,
    quip: (strings) => strings.quipHireCleaner,
    explanation: (strings) => strings.explainHireCleaner,
    source: 'SVT Nyheter',
    sourceUrl: 'https://www.svt.se/nyheter/inrikes/det-har-kanske-du-inte-visste-om-ulf-kristersson',
    basePrice: 100,
    incomePerSecond: 2,
    tier: 0,
    branch: 1,
  ),
  SkillDef(
    id: SkillId.cheatApartment,
    iconPath: AssetPaths.iconHouse,
    name: (strings) => strings.itemCheatApartment,
    quip: (strings) => strings.quipCheatApartment,
    explanation: (strings) => strings.explainCheatApartment,
    source: 'SVT Nyheter',
    sourceUrl: 'https://www.svt.se/nyheter/inrikes/nya-ministern-fick-hyresratt-genom-kontakter',
    basePrice: 250,
    incomePerSecond: 5,
    tier: 1,
    branch: 0,
    requires: SkillId.hireCleaner,
  ),
  SkillDef(
    id: SkillId.taxiRides,
    iconPath: AssetPaths.iconStopwatch,
    name: (strings) => strings.itemTaxiRides,
    quip: (strings) => strings.quipTaxiRides,
    explanation: (strings) => strings.explainTaxiRides,
    source: 'SVT Nyheter',
    sourceUrl: 'https://www.svt.se/nyheter/lokalt/sormland/manga-taxiresor-for-kristersson',
    basePrice: 3000,
    incomePerSecond: 30,
    tier: 2,
    branch: 0,
    requires: SkillId.cheatApartment,
  ),
  SkillDef(
    id: SkillId.chinaTrips,
    iconPath: AssetPaths.iconShoe,
    name: (strings) => strings.itemChinaTrips,
    quip: (strings) => strings.quipChinaTrips,
    explanation: (strings) => strings.explainChinaTrips,
    source: 'Dagens Arena',
    sourceUrl:
        'https://www.dagensarena.se/innehall/ulf-kristersson-kritiserad-forr/',
    basePrice: 20000,
    incomePerSecond: 150,
    tier: 3,
    branch: 0,
    requires: SkillId.taxiRides,
  ),
  SkillDef(
    id: SkillId.furnishPalace,
    iconPath: AssetPaths.iconTrophy,
    name: (strings) => strings.itemFurnishPalace,
    quip: (strings) => strings.quipFurnishPalace,
    explanation: (strings) => strings.explainFurnishPalace,
    source: 'Eskilstuna-Kuriren',
    sourceUrl: 'https://www.ekuriren.se/nyheter/strangnas/artikel/granskning-av-dyra-konsultinkop-till-sagerska-palatset/r24qw4vj',
    basePrice: 150000,
    incomePerSecond: 900,
    tier: 4,
    branch: 0,
    requires: SkillId.chinaTrips,
  ),
  SkillDef(
    id: SkillId.writeBook,
    iconPath: AssetPaths.iconBook,
    name: (strings) => strings.itemWriteBook,
    quip: (strings) => strings.quipWriteBook,
    explanation: (strings) => strings.explainWriteBook,
    source: 'SVT Nyheter',
    sourceUrl: 'https://www.svt.se/nyheter/inrikes/det-har-kanske-du-inte-visste-om-ulf-kristersson',
    basePrice: 750,
    clickFactor: 2,
    growth: 5,
    tier: 1,
    branch: 1,
    requires: SkillId.hireCleaner,
  ),
  SkillDef(
    id: SkillId.lowerTaxes,
    iconPath: AssetPaths.iconDiamond,
    name: (strings) => strings.itemLowerTaxes,
    quip: (strings) => strings.quipLowerTaxes,
    explanation: (strings) => strings.explainLowerTaxes,
    source: 'SVT Nyheter',
    sourceUrl: 'https://www.svt.se/nyheter/inrikes/regeringen-har-gynnat-man-och-hoginkomsttagare',
    basePrice: 12500,
    clickFactor: 3,
    growth: 5,
    tier: 2,
    branch: 1,
    requires: SkillId.writeBook,
  ),
  SkillDef(
    id: SkillId.breakPromise,
    iconPath: AssetPaths.iconBrokenHeart,
    name: (strings) => strings.itemBreakPromise,
    quip: (strings) => strings.quipBreakPromise,
    explanation: (strings) => strings.explainBreakPromise,
    source: 'SVT Nyheter',
    sourceUrl: 'https://www.svt.se/nyheter/inrikes/avgaende-c-partiledaren-om-kristerssons-m-lofte-stort-svek',
    basePrice: 750000,
    clickFactor: 4,
    growth: 5,
    tier: 3,
    branch: 1,
    requires: SkillId.lowerTaxes,
  ),
  SkillDef(
    id: SkillId.cutSickLeave,
    iconPath: AssetPaths.iconCalendar,
    name: (strings) => strings.itemCutSickLeave,
    quip: (strings) => strings.quipCutSickLeave,
    explanation: (strings) => strings.explainCutSickLeave,
    source: 'Inspektionen för socialförsäkringen',
    sourceUrl: 'https://isf.se/publikationer/rapporter/2022/2022-06-29-avskaffandet-av-den-bortre-tidsgransen',
    basePrice: 5000000,
    clickFactor: 5,
    growth: 5,
    tier: 4,
    branch: 1,
    requires: SkillId.breakPromise,
  ),
  SkillDef(
    id: SkillId.privatizeSchools,
    iconPath: AssetPaths.iconPencil,
    name: (strings) => strings.itemPrivatizeSchools,
    quip: (strings) => strings.quipPrivatizeSchools,
    explanation: (strings) => strings.explainPrivatizeSchools,
    source: 'SVT Nyheter',
    sourceUrl: 'https://www.svt.se/nyheter/utrikes/forbud-mot-friskolor-ska-oka-jamstalldheten-i-chile',
    basePrice: 10000,
    incomePerSecond: 100,
    tier: 1,
    branch: 2,
    requires: SkillId.hireCleaner,
  ),
  SkillDef(
    id: SkillId.privatizeHospitals,
    iconPath: AssetPaths.iconPotion,
    name: (strings) => strings.itemPrivatizeHospitals,
    quip: (strings) => strings.quipPrivatizeHospitals,
    explanation: (strings) => strings.explainPrivatizeHospitals,
    source: 'Wikipedia',
    sourceUrl: 'https://sv.wikipedia.org/wiki/Sankt_G%C3%B6rans_sjukhus',
    basePrice: 60000,
    incomePerSecond: 450,
    tier: 2,
    branch: 2,
    requires: SkillId.privatizeSchools,
  ),
  SkillDef(
    id: SkillId.sellPreschools,
    iconPath: AssetPaths.iconBabyClothes,
    name: (strings) => strings.itemSellPreschools,
    quip: (strings) => strings.quipSellPreschools,
    explanation: (strings) => strings.explainSellPreschools,
    source: 'Sveriges Radio',
    sourceUrl: 'https://sverigesradio.se/artikel/4063990',
    basePrice: 350000,
    incomePerSecond: 2200,
    tier: 3,
    branch: 2,
    requires: SkillId.privatizeHospitals,
  ),
  SkillDef(
    id: SkillId.sellPublicHousing,
    iconPath: AssetPaths.iconEnvelope,
    name: (strings) => strings.itemSellPublicHousing,
    quip: (strings) => strings.quipSellPublicHousing,
    explanation: (strings) => strings.explainSellPublicHousing,
    source: 'Sveriges Radio',
    sourceUrl: 'https://www.sverigesradio.se/artikel/1960541',
    basePrice: 2000000,
    incomePerSecond: 11000,
    tier: 4,
    branch: 2,
    requires: SkillId.sellPreschools,
  ),
];

SkillDef skillById(SkillId id) =>
    skillCatalog.firstWhere((skill) => skill.id == id);
