import 'package:fifflar_uffe/game/assets.dart';
import 'package:fifflar_uffe/model/skill_def.dart';

final List<SkillDef> skillCatalog = [
  SkillDef(
    id: 'hire_cleaner',
    iconPath: AssetPaths.iconPeople,
    name: (strings) => strings.itemHireCleaner,
    quip: (strings) => strings.quipHireCleaner,
    explanation: (strings) => strings.explainHireCleaner,
    source: 'Dagens Arena',
    sourceUrl:
        'https://www.dagensarena.se/innehall/ulf-kristersson-kritiserad-forr/',
    basePrice: 100,
    incomePerSecond: 2,
    tier: 0,
    branch: 1,
  ),
  SkillDef(
    id: 'cheat_apartment',
    iconPath: AssetPaths.iconHouse,
    name: (strings) => strings.itemCheatApartment,
    quip: (strings) => strings.quipCheatApartment,
    explanation: (strings) => strings.explainCheatApartment,
    source: 'Aktuellt Fokus',
    sourceUrl: 'https://aktuelltfokus.se/ulf-kristerssons-varsta-korruptions-skandaler/',
    basePrice: 250,
    incomePerSecond: 5,
    tier: 1,
    branch: 0,
    requires: 'hire_cleaner',
  ),
  SkillDef(
    id: 'taxi_rides',
    iconPath: AssetPaths.iconStopwatch,
    name: (strings) => strings.itemTaxiRides,
    quip: (strings) => strings.quipTaxiRides,
    explanation: (strings) => strings.explainTaxiRides,
    source: 'Morgontidningen',
    sourceUrl: 'https://morgontidningen.se/2025/01/ulf-kristersson-skandaler/',
    basePrice: 3000,
    incomePerSecond: 30,
    tier: 2,
    branch: 0,
    requires: 'cheat_apartment',
  ),
  SkillDef(
    id: 'china_trips',
    iconPath: AssetPaths.iconShoe,
    name: (strings) => strings.itemChinaTrips,
    quip: (strings) => strings.quipChinaTrips,
    explanation: (strings) => strings.explainChinaTrips,
    source: 'Aktuellt Fokus',
    sourceUrl: 'https://aktuelltfokus.se/ulf-kristerssons-varsta-korruptions-skandaler/',
    basePrice: 20000,
    incomePerSecond: 150,
    tier: 3,
    branch: 0,
    requires: 'taxi_rides',
  ),
  SkillDef(
    id: 'furnish_palace',
    iconPath: AssetPaths.iconTrophy,
    name: (strings) => strings.itemFurnishPalace,
    quip: (strings) => strings.quipFurnishPalace,
    explanation: (strings) => strings.explainFurnishPalace,
    source: 'Eskilstuna-Kuriren',
    sourceUrl: 'https://www.ekuriren.se/nyheter/strangnas/artikel/granskning-av-dyra-konsultinkop-till-sagerska-palatset/r24qw4vj',
    basePrice: 150000,
    incomePerSecond: 900,
    tier: 4,
    branch: 0,
    requires: 'china_trips',
  ),
  SkillDef(
    id: 'write_book',
    iconPath: AssetPaths.iconBook,
    name: (strings) => strings.itemWriteBook,
    quip: (strings) => strings.quipWriteBook,
    explanation: (strings) => strings.explainWriteBook,
    source: 'Dagens Arena',
    sourceUrl: 'https://www.dagensarena.se/innehall/ulf-kristersson-den-svenska-modellen-ar-som-apartheid/',
    basePrice: 1500,
    clickBonus: 1,
    tier: 1,
    branch: 1,
    requires: 'hire_cleaner',
  ),
  SkillDef(
    id: 'lower_taxes',
    iconPath: AssetPaths.iconDiamond,
    name: (strings) => strings.itemLowerTaxes,
    quip: (strings) => strings.quipLowerTaxes,
    explanation: (strings) => strings.explainLowerTaxes,
    source: 'Dagens Arena',
    sourceUrl:
        'https://www.dagensarena.se/redaktionen/best-of-ulf-kristersson/',
    basePrice: 25000,
    clickBonus: 2,
    tier: 2,
    branch: 1,
    requires: 'write_book',
  ),
  SkillDef(
    id: 'break_promise',
    iconPath: AssetPaths.iconBrokenHeart,
    name: (strings) => strings.itemBreakPromise,
    quip: (strings) => strings.quipBreakPromise,
    explanation: (strings) => strings.explainBreakPromise,
    source: 'SVT Nyheter',
    sourceUrl: 'https://www.svt.se/nyheter/inrikes/avgaende-c-partiledaren-om-kristerssons-m-lofte-stort-svek',
    basePrice: 1500000,
    clickBonus: 5,
    tier: 3,
    branch: 1,
    requires: 'lower_taxes',
  ),
  SkillDef(
    id: 'cut_sick_leave',
    iconPath: AssetPaths.iconCalendar,
    name: (strings) => strings.itemCutSickLeave,
    quip: (strings) => strings.quipCutSickLeave,
    explanation: (strings) => strings.explainCutSickLeave,
    source: 'Equal',
    sourceUrl: 'https://equalsthlm.se/artiklar/ulf-kristerssons-sjukpenningspolitik-misslyckades/',
    basePrice: 10000000,
    clickBonus: 10,
    tier: 4,
    branch: 1,
    requires: 'break_promise',
  ),
  SkillDef(
    id: 'privatize_schools',
    iconPath: AssetPaths.iconPencil,
    name: (strings) => strings.itemPrivatizeSchools,
    quip: (strings) => strings.quipPrivatizeSchools,
    explanation: (strings) => strings.explainPrivatizeSchools,
    source: 'Dagens Arena',
    sourceUrl: 'https://www.dagensarena.se/essa/marknadsskolans-basta-forsvar-att-skapa-forvirring/',
    basePrice: 10000,
    incomePerSecond: 100,
    tier: 1,
    branch: 2,
    requires: 'hire_cleaner',
  ),
  SkillDef(
    id: 'privatize_hospitals',
    iconPath: AssetPaths.iconPotion,
    name: (strings) => strings.itemPrivatizeHospitals,
    quip: (strings) => strings.quipPrivatizeHospitals,
    explanation: (strings) => strings.explainPrivatizeHospitals,
    source: 'Wikipedia',
    sourceUrl: 'https://sv.wikipedia.org/wiki/Sankt_G%C3%B6rans_sjukhus',
    basePrice: 60000,
    incomePerSecond: 450,
    tier: 2,
    branch: 2,
    requires: 'privatize_schools',
  ),
  SkillDef(
    id: 'sell_preschools',
    iconPath: AssetPaths.iconBabyClothes,
    name: (strings) => strings.itemSellPreschools,
    quip: (strings) => strings.quipSellPreschools,
    explanation: (strings) => strings.explainSellPreschools,
    source: 'Sveriges Radio',
    sourceUrl: 'https://sverigesradio.se/artikel/4063990',
    basePrice: 350000,
    incomePerSecond: 2200,
    tier: 3,
    branch: 2,
    requires: 'privatize_hospitals',
  ),
  SkillDef(
    id: 'sell_public_housing',
    iconPath: AssetPaths.iconEnvelope,
    name: (strings) => strings.itemSellPublicHousing,
    quip: (strings) => strings.quipSellPublicHousing,
    explanation: (strings) => strings.explainSellPublicHousing,
    source: 'Dagens Arena',
    sourceUrl: 'https://www.dagensarena.se/essa/40-ar-av-privatiserad-allmannytta-stockholm/',
    basePrice: 2000000,
    incomePerSecond: 11000,
    tier: 4,
    branch: 2,
    requires: 'sell_preschools',
  ),
];

SkillDef skillById(String id) =>
    skillCatalog.firstWhere((skill) => skill.id == id);
